"""update_invoice_columns

Revision ID: 33eafb6280f4
Revises: ee55109705e6
Create Date: 2026-06-07 11:03:55.946949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33eafb6280f4'
down_revision: Union[str, None] = 'ee55109705e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.add_column('invoices', sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('transaction_reference', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'invoices', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'tax')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('tax', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('discount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'issued_at')
    op.drop_column('invoices', 'transaction_reference')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'balance_due')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'line_items')
    op.drop_column('invoices', 'patient_id')
    # ### end Alembic commands ###