"""update_doctor_columns

Revision ID: b6ef9dd40582
Revises: 9de4945a11f4
Create Date: 2026-06-07 09:46:41.410706

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6ef9dd40582'
down_revision: str | None = '9de4945a11f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('doctors', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('doctors', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=False))
    op.add_column('doctors', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('doctors', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('doctors', 'name')
    op.drop_column('doctors', 'avg_consultation_minutes')
    op.drop_column('doctors', 'is_available')
    op.drop_column('doctors', 'bio')
    op.drop_column('doctors', 'follow_up_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('follow_up_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('avg_consultation_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('doctors', 'is_active')
    op.drop_column('doctors', 'experience_years')
    op.drop_column('doctors', 'registration_number')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'phone')
    op.drop_column('doctors', 'gender')
    op.drop_column('doctors', 'last_name')
    op.drop_column('doctors', 'first_name')
    # ### end Alembic commands ###
