"""update_patient_columns

Revision ID: ee55109705e6
Revises: b6ef9dd40582
Create Date: 2026-06-07 10:17:47.318325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee55109705e6'
down_revision: Union[str, None] = 'b6ef9dd40582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('patients', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('existing_conditions', sa.Text(), nullable=True))
    op.drop_column('patients', 'medical_notes')
    op.drop_column('patients', 'name')
    op.drop_column('patients', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('medical_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'existing_conditions')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    # ### end Alembic commands ###